export type AdminLang = "en" | "th";

const tr = {
  en: {
    dashboard: "Dashboard",
    menu: "Menu",
    campaigns: "Campaigns",
    gallery: "Gallery",
    signOut: "Sign Out",
    adminLogin: "Admin Login",
    managementSubtitle: "Jiknaam Cafe Management",
    email: "Email",
    password: "Password",
    emailRequired: "Email is required",
    passwordRequired: "Password is required",
    invalidCredentials: "Invalid email or password.",
    signingIn: "Signing in...",
    signIn: "Sign In",
    menuItems: "Menu Items",
    galleryImages: "Gallery Images",
    manage: "Manage →",
    addItem: "Add Item",
    editItem: "Edit Item",
    noItems: "No items found.",
    nameEn: "Name (EN)",
    nameTh: "Name (TH)",
    descEn: "Description (EN)",
    descTh: "Description (TH)",
    price: "Price (฿)",
    category: "Category",
    imageUrl: "Image URL (placeholder)",
    uploadImage: "Upload Image (overrides URL)",
    cancel: "Cancel",
    saving: "Saving...",
    save: "Save",
    deleteMenuConfirm: "Delete this menu item?",
    required: "Required",
    addCampaign: "Add Campaign",
    editCampaign: "Edit Campaign",
    noCampaigns: "No campaigns yet.",
    titleEn: "Title (EN)",
    titleTh: "Title (TH)",
    imageUrlShort: "Image URL",
    activeLabel: "Active (visible on website)",
    active: "Active",
    inactive: "Inactive",
    deleteCampaignConfirm: "Delete this campaign?",
    uploading: "Uploading...",
    uploadImages: "Upload Images",
    clickToUpload: "Click to upload images",
    removeImageConfirm: "Remove this image from the gallery?",
  },
  th: {
    dashboard: "แดชบอร์ด",
    menu: "เมนู",
    campaigns: "แคมเปญ",
    gallery: "แกลเลอรี",
    signOut: "ออกจากระบบ",
    adminLogin: "เข้าสู่ระบบแอดมิน",
    managementSubtitle: "จัดการร้าน Jiknaam Cafe",
    email: "อีเมล",
    password: "รหัสผ่าน",
    emailRequired: "กรุณากรอกอีเมล",
    passwordRequired: "กรุณากรอกรหัสผ่าน",
    invalidCredentials: "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
    signingIn: "กำลังเข้าสู่ระบบ...",
    signIn: "เข้าสู่ระบบ",
    menuItems: "รายการเมนู",
    galleryImages: "รูปภาพแกลเลอรี",
    manage: "จัดการ →",
    addItem: "เพิ่มรายการ",
    editItem: "แก้ไขรายการ",
    noItems: "ไม่พบรายการ",
    nameEn: "ชื่อ (EN)",
    nameTh: "ชื่อ (TH)",
    descEn: "คำอธิบาย (EN)",
    descTh: "คำอธิบาย (TH)",
    price: "ราคา (฿)",
    category: "หมวดหมู่",
    imageUrl: "URL รูปภาพ",
    uploadImage: "อัปโหลดรูปภาพ (แทนที่ URL)",
    cancel: "ยกเลิก",
    saving: "กำลังบันทึก...",
    save: "บันทึก",
    deleteMenuConfirm: "ลบรายการนี้?",
    required: "จำเป็น",
    addCampaign: "เพิ่มแคมเปญ",
    editCampaign: "แก้ไขแคมเปญ",
    noCampaigns: "ยังไม่มีแคมเปญ",
    titleEn: "ชื่อ (EN)",
    titleTh: "ชื่อ (TH)",
    imageUrlShort: "URL รูปภาพ",
    activeLabel: "เปิดใช้งาน (แสดงบนเว็บไซต์)",
    active: "เปิดใช้",
    inactive: "ปิดใช้",
    deleteCampaignConfirm: "ลบแคมเปญนี้?",
    uploading: "กำลังอัปโหลด...",
    uploadImages: "อัปโหลดรูปภาพ",
    clickToUpload: "คลิกเพื่ออัปโหลดรูปภาพ",
    removeImageConfirm: "ลบรูปภาพนี้ออกจากแกลเลอรี?",
  },
} as const;

export type TranslationKey = keyof typeof tr.en;

export function getT(lang: AdminLang) {
  return (key: TranslationKey): string => tr[lang][key];
}
